statusicon: use absolute delta to find the nearest icon size
Otherwise, if we only look at (pixel_size - stock_size), we miss the
case when the pixel size is smaller than any provided stock size.

https://bugzilla.gnome.org/show_bug.cgi?id=673749

statusicon: Fix implicit declaration warning

gtkstatusicon.c:1333:4: warning: implicit declaration of function 'abs' [-Wimplicit-function-declaration]

Added in commit c8378099600e4279cb5c608b546bbe778c451233

Gbp-Pq: Name 072_statusicon_icon_size.patch